version: '3.3'
services:
  backend:
    restart: always
    build: ./backend/

  frontend:
    restart: always
    build: ./frontend/
    links:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:8080"
