version: '3.8'
services:
  ansible-deployment:
    network_mode: "host"
    build: .
    environment:
      - ANSIBLE_HOST=${ANSIBLE_HOST}
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
